version = "2.0.2"
group = "at.yedel.advantimations"

# `versions`: The actual version to use in development
# `targets`: The dependency to target in fabric.mod.json

versions.fabricLoader = "0.18.4"
targets.fabricLoader = "*"

["26.1.1"]
targets.minecraft = ">=26.1 <=26.1.1"

versions.fabricApi = "0.145.3+26.1.1"
targets.fabricApi = "*"
versions.modMenu = "18.0.0-alpha.8"
# unused
targets.modMenu = "*"
versions.yacl = "3.9.2+26.1-fabric"
targets.yacl = "*"
