# `versions`: The actual version to use in development
# `targets`: The dependency to target in fabric.mod.json

version = "2.0.2"
group = "at.yedel.advantimations"

versions.fabricLoader = "0.19.0"
targets.fabricLoader = ">=0.18.4"

["26.1.1"]
mc.min = "26.1"
mc.max = "26.1.1"

versions.fabricApi = "0.145.3+26.1.1"
targets.fabricApi = "*"
versions.modMenu = "18.0.0-alpha.8"
# unused
targets.modMenu = "*"
versions.yacl = "3.9.2+26.1-fabric"
targets.yacl = ">=3.9.2+26.1-fabric"
